name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git

    - name: Build and install googletest (CI fallback)
      run: |
        git clone https://github.com/google/googletest.git /tmp/googletest
        cmake -S /tmp/googletest -B /tmp/googletest/build
        cmake --build /tmp/googletest/build --config Release -j
        sudo cmake --install /tmp/googletest/build

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release -- -j

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
